version: "1"
services:
  web:
    image: "goudafriends/shopping-cart-client"
    ports:
      - "1234:1234"
    container_name: goudafriends-shopping-cart-web
  api:
    image: "goudafriends/shopping-cart-server"
    ports:
      - "5001:5001"
    env_file: .env
    container_name: goudafriends-shopping-cart-api